#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

sudo apt update -y

sudo apt-get install -y python3 python3-dev python3-venv python3-pip bluez libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf build-essential libopenjp2-7 libtiff6 libturbojpeg0-dev tzdata ffmpeg liblapack3 liblapack-dev libatlas-base-dev

python3 -m pip install --requirement requirements.txt

python3 -m pip install wheel
